repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: golangci-lint
        args: [--disable-all, --enable=goimports, --enable=golint, --enable=vet, --enable=ineffassign]

  - repo: local
    hooks:
      - id: check-bin-version
        name: Check bundle packages
        entry: .scripts/pre-commit-bundle-check.sh
        language: script
        files: ^bin/
