repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-vet
      - id: golangci-lint

  - repo: local
    hooks:
      - id: check-bin-version
        name: Check bundle packages
        entry: .scripts/pre-commit-bundle-check.sh
        language: script
        files: ^bin/*
